### ISSUE TITLE
presented server name type wasn't supported on GKE

### ISSUE THREAD

**Issue by tamasfe** [metalbear-co/mirrord#388] opened 2022-09-11 17:52 UTC
### Bug Description

`kube_client::client::builder: failed with error error trying to connect: presented server name type wasn't supported` is reported when connecting to a GKE cluster.

`--accept-invalid-certificates` as suggested is a good workaround but the certificate is definitely valid.

If you are using rustls, I suspect it's https://github.com/rustls/rustls/issues/184.

### Steps to Reproduce

1. `gcloud container clusters get-credentials foo`: load cluster credentials into `.kube/config`
2. `k describe node`: kubectl connects successfully
3. try to `mirrord exec` anything in the cluster

### Your operating system and version

Linux 5.19.7-arch1-1

### Local process

/bin/bash

**Comment by aviramha** [comment] 2022-09-12 06:24
Thanks for reporting it - as you suggested, it's because of rustls We had problems linking to OpenSSL as the running binary might have another version required leading to crashes so we have to use rustls. 
It seems that the rustls issue is a bit complicated (requires changes on dependencies that are still pending). I'll try to see if we can push something there or help somehow.

**Comment by eyalb181** [comment] 2022-09-22 13:17
Hey @tamasfe, this should be fixed in the latest version. Please let us know if it reproduces.

**Closed by eyalb181** 2022-09-22 13:17 UTC
Labels: bug, user
