### ISSUE TITLE
`ERROR: transport error 202: connect failed: Unknown error: 111` when debugging a JVM-app

### ISSUE THREAD

**Issue by jamowei** [metalbear-co/mirrord#644] opened 2022-10-26 18:27 UTC
### Bug Description

I get the following error when I set the `MIRRORD_TCP_OUTGOING` to `true` on macOS an and a JVM-based service:
```
2022-10-26T18:13:26.498142Z  INFO ThreadId(01) mirrord_layer::go_env: replace -> hooking "runtime.goenvs_unix"
2022-10-26T18:13:26.688625Z  INFO ThreadId(15) mirrord_layer::socket::hooks: 14
2022-10-26T18:13:26.718586Z  INFO ThreadId(15) mirrord_layer::error: libc error (doesn't indicate a problem) >> ResponseError(
    RemoteIO(
        RemoteIOError {
            raw_os_error: Some(
                111,
            ),
            kind: ConnectionRefused,
        },
    ),
)
ERROR: transport error 202: connect failed: Unknown error: 111
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [./src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:735]

Process finished with exit code 2
```

Here are my env vars which I'm using:
```
DYLD_INSERT_LIBRARIES=/Users/jamowei/Library/Application Support/JetBrains/IntelliJIdea2022.2/plugins/mirrord/libmirrord_layer.dylib
LD_PRELOAD=/Users/jamowei/Library/Application Support/JetBrains/IntelliJIdea2022.2/plugins/mirrord/libmirrord_layer.so
MIRRORD_AGENT_RUST_LOG=DEBUG
RUST_LOG=DEBUG
MIRRORD_ACCEPT_INVALID_CERTIFICATES=true
MIRRORD_EPHEMERAL_CONTAINER=false
MIRRORD_SKIP_PROCESSES=
MIRRORD_OVERRIDE_ENV_VARS_INCLUDE=*
MIRRORD_IMPERSONATED_TARGET=pod/my-service-xxx
MIRRORD_TARGET_NAMESPACE=mynamespace
MIRRORD_FILE_OPS=false
MIRRORD_AGENT_TCP_STEAL_TRAFFIC=false
MIRRORD_REMOTE_DNS=true
MIRRORD_TCP_OUTGOING=true
MIRRORD_UDP_OUTGOING=false
```

When I set `MIRRORD_TCP_OUTGOING` to `false` mirroring works as expected.

### Steps to Reproduce

1. set `MIRRORD_TCP_OUTGOING`to `true`
2. start `mirrord exec` with the JVM-based server
3. get the error message

### Relevant Logs

```shell
2022-10-26T18:22:08.185829Z TRACE ThreadId(11) tungstenite::protocol: Frames still in queue: 0    
2022-10-26T18:22:08.185827Z TRACE ThreadId(02) handle_daemon_message: mirrord_layer: enter daemon_message=TcpOutgoing(Connect(Err(RemoteIO(RemoteIOError { raw_os_error: Some(111), kind: ConnectionRefused }))))
2022-10-26T18:22:08.185831Z TRACE ThreadId(11) tokio_tungstenite::compat: /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-tungstenite-0.17.2/src/compat.rs:149 Read.read    
2022-10-26T18:22:08.185834Z TRACE ThreadId(11) tokio_tungstenite::compat: /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-tungstenite-0.17.2/src/compat.rs:126 AllowStd.with_context    
2022-10-26T18:22:08.185836Z TRACE ThreadId(11) tokio_tungstenite::compat: /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-tungstenite-0.17.2/src/compat.rs:152 Read.with_context read -> poll_read    
2022-10-26T18:22:08.185839Z TRACE ThreadId(11) tokio_tungstenite::compat: WouldBlock    
2022-10-26T18:22:08.185842Z TRACE ThreadId(02) handle_daemon_message:handle_daemon_message: mirrord_layer::outgoing::tcp: enter daemon_message=TcpOutgoing(Connect(Err(RemoteIO(RemoteIOError { raw_os_error: Some(111), kind: ConnectionRefused })))) response=Connect(Err(RemoteIO(RemoteIOError { raw_os_error: Some(111), kind: ConnectionRefused })))
2022-10-26T18:22:08.185850Z TRACE ThreadId(02) handle_daemon_message:handle_daemon_message: mirrord_layer::outgoing::tcp: Connect -> connect Err(
    RemoteIO(
        RemoteIOError {
            raw_os_error: Some(
                111,
            ),
            kind: ConnectionRefused,
        },
    ),
) daemon_message=TcpOutgoing(Connect(Err(RemoteIO(RemoteIOError { raw_os_error: Some(111), kind: ConnectionRefused })))) response=Connect(Err(RemoteIO(RemoteIOError { raw_os_error: Some(111), kind: ConnectionRefused })))
2022-10-26T18:22:08.185866Z TRACE ThreadId(02) handle_daemon_message:handle_daemon_message: mirrord_layer::outgoing::tcp: exit daemon_message=TcpOutgoing(Connect(Err(RemoteIO(RemoteIOError { raw_os_error: Some(111), kind: ConnectionRefused })))) response=Connect(Err(RemoteIO(RemoteIOError { raw_os_error: Some(111), kind: ConnectionRefused })))
2022-10-26T18:22:08.185871Z TRACE ThreadId(02) handle_daemon_message: mirrord_layer: exit daemon_message=TcpOutgoing(Connect(Err(RemoteIO(RemoteIOError { raw_os_error: Some(111), kind: ConnectionRefused }))))
2022-10-26T18:22:08.185876Z TRACE ThreadId(02) actix_codec::framed: attempting to decode a frame    
2022-10-26T18:22:08.185906Z TRACE ThreadId(15) connect: mirrord_layer::socket::ops: exit sockfd=14 raw_address=0x70000bc22590 address_length=16
2022-10-26T18:22:08.185912Z  INFO ThreadId(15) mirrord_layer::error: libc error (doesn't indicate a problem) >> ResponseError(
    RemoteIO(
        RemoteIOError {
            raw_os_error: Some(
                111,
            ),
            kind: ConnectionRefused,
        },
    ),
)
ERROR: transport error 202: connect failed: Unknown error: 111
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [./src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:735]

Process finished with exit code 2
```

### Your operating system and version

macOS 12.6

### Local process

/usr/bin/java: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64 - Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e - Mach-O 64-bit executable arm64e]

### Local process version

openjdk version "11.0.15" 2022-04-19 LTS OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS) OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)

**Comment by aviramha** [comment] 2022-10-26 18:39
Thanks for reporting this @jamowei.
Can you please tell us what Java framework do you use? if you can provide some minimal reproducible program it can bee awesome!

**Comment by jamowei** [comment] 2022-10-27 11:39
Ok, I will try to create a small app to reproduce the error.

**Comment by jamowei** [comment] 2022-10-27 16:04
Hi, I tested it today with the current mirrord 3.4.0 version and the intelliJ extension and the error is gone! Thanks for the good work! 👍🏻

**Comment by jamowei** [comment] 2022-10-28 11:34
Hi,

I dig deeper into this problem, and found out that this is a problem only occurs when using the IntelliJ debugging of a JVM-based application and mirrord in conjunction.
That is why it created a simple java sever app for testing and reproduce the problem in IntelliJ: https://github.com/jamowei/simple-java-server
In there, I use the same mechanism as the IntelliJ extension by providing the needed env vars.
In the shell-script `run_env.sh` you can see the different commands IntelliJ runs, when you click on `Run` or `Debug`.
The application fails when you choose the second command, which is the same as using the `Debug` functionality in IntelliJ.

In JVM-based apps the debugging is done by spawning a second process (agent) with an own debugging-port which then the debug-application like IntelliJ can connect with. In this example, it is `127.0.0.1:50547`. I suppose that mirrord is hooking this port too, which then results in the error after startup, because the debugging-app couldn't communicate with the debug-agent anymore.

Is there is a possibility to exclude the debug-port from mirrord? Then I can try to find out the debug-port in the IntelliJ extension and put it a corresponding env var. Then I would assume that the error should not be occur anymore :-)

**Comment by aviramha** [comment] 2022-10-28 12:13
hi @jamowei 
Nice catch! It can be fixed using the env var `MIRRORD_SKIP_PROCESSES` that is used to avoid other debuggers in other languages as well (see `GoRunConfig.kt` for an example).
I will prioritize the fix, or if you wish you can send a PR (it should be easy -> detect if it's a debug launch of Java, and if so add the debugger process name to the MIRRORD_SKIP_PROCESSES env var)

**Comment by jamowei** [comment] 2022-10-28 12:43
Ah ok, thanks I will try!

**Comment by jamowei** [comment] 2022-10-28 13:29
Sadly, this would not be so easy, because the IntelliJ launches no extra process for debugging:

processes which uses the debug-port:
```
> lsof -i :49580
COMMAND  PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
idea     663 jamowei  402u  IPv6 0xae215edc3cb1ddf7      0t0  TCP localhost:49580->localhost:49581 (ESTABLISHED)
java    2887 jamowei    5u  IPv4 0xae215ee5d772d93f      0t0  TCP localhost:49581->localhost:49580 (ESTABLISHED)
```
processes which uses the application-port:
```
> lsof -i :8080 
COMMAND  PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
java    2887 jamowei    8u  IPv6 0xae215edc3cb121f7      0t0  TCP *:http-alt (LISTEN)
```
process tree-view:
```
> pstree -p 2887 
-+= 00001 root /sbin/launchd
 \-+= 00663 jamowei /Applications/IntelliJ IDEA.app/Contents/MacOS/idea
   \--- 02887 jamowei /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:49580,suspend=y,server=n -javaagent:/Users/jamowei/Library/Cach
```
The debug-agent is launched inside the java application-process and not as an extra process by the JVM...

**Comment by aviramha** [comment] 2022-10-28 15:18
P.S our team is on it.

**Comment by jamowei** [comment] 2022-10-28 17:44
Yeah, IntelliJ is connecting to the port spawned by the debug-agent after setting the jvm debug-option. I think when the connection could not be established, because of mirrord intercepting the error is thrown. When I turn off the outgoing feature of mirrod debugging works as normal. Sadly IntelliJ picks a random port everytime you start a new debug-session... But perhaps there is a way to pick the port in the IntelliJ extension when starting a debug-session and set it as env var!?

**Comment by jamowei** [comment] 2022-10-28 18:01
I found out that when you use server-mode of the debug-agent by setting `server=y` instead of `server=n`
```
$JAVA_HOME/bin/java \
 -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:50547,suspend=y,server=y \
 -javaagent:"/Users/jamowei/Library/Caches/JetBrains/IntelliJIdea2022.2/captureAgent/debugger-agent.jar" \
 -Dfile.encoding=UTF-8 \
 -classpath $PWD/target/classes:"/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar" \
 SimpleServer
```
it also works with mirrord and outgoing feature enabled.
To begin with debuggin then, I have to start an extra remote debug session on the port `50547` in IntelliJ.
<img width="768" alt="image" src="https://user-images.githubusercontent.com/29158537/198702285-a3821344-c0a9-47c0-bced-689ca3dff8fa.png">

**Comment by infiniteregrets** [comment] 2022-10-28 18:11
> I found out that when you use server-mode of the debug-agent by setting `server=y` instead of `server=n`
> 
> ```
> $JAVA_HOME/bin/java \
>  -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:50547,suspend=y,server=y \
>  -javaagent:"/Users/jamowei/Library/Caches/JetBrains/IntelliJIdea2022.2/captureAgent/debugger-agent.jar" \
>  -Dfile.encoding=UTF-8 \
>  -classpath $PWD/target/classes:"/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar" \
>  SimpleServer
> ```
> 
> it also works with mirrord and outgoing feature enabled. To begin with debuggin then, I have to start an extra remote debug session on the port `50547` in IntelliJ. <img alt="image" width="768" src="https://user-images.githubusercontent.com/29158537/198702285-a3821344-c0a9-47c0-bced-689ca3dff8fa.png">

thanks for the elaborate response! I am assuming this works because, we already ignore ports in range of 50K - 60K. It won't probably wont work If you specify a port beyond this range whose socket we don't keep track of

**Comment by jamowei** [comment] 2022-10-28 20:04
Ah ok, that explains why it sometimes work and sometimes not! When IntelliJ randomly pick a port > 5000 it works otherwise < 5000 not.

**Comment by infiniteregrets** [comment] 2022-11-01 22:09
hey @jamowei, the patch was merged. Hopefully, it should work for you now!
There will be an elaborate API for dealing with ports just like files soon, so keeping this issue open.
Thanks for the report again!

**Closed** 2022-11-08 11:51 UTC
Labels: bug
