### ISSUE TITLE
golang syscall interception issue the app is using BoltDB

### ISSUE THREAD

**Issue by Ngalstyan4** [metalbear-co/mirrord#2099] opened 2023-12-06 08:38 UTC
### Bug Description

Hi,

I have been trying to use `mirrord` with my application and and continually was getting errors when running with mirrord while not getting the same errors without mirrord

I tracked the issue down to etcd, and then to BoltDB inside etcd.

Consider the following golang application

```golang
package main

import (
        "C"
        "log"
        bolt "go.etcd.io/bbolt"
)

func main() {
        // Open the BoltDB file
        db, err := bolt.Open("hello.db", 777, nil)
        if err != nil {
                log.Fatal(err)
        }
        defer db.Close()
}
```
I compile this with `go mod tidy && go build`. 
I have tried `go build -ldflags "-linkmode 'external' -extldflags '-dynamic'"` as well ([details here](https://mt165.co.uk/blog/static-link-go/)). That does not change the outcome.

Compiler info:
```
$ go version
go version go1.20.3 linux/amd64
```

When run with mirrord, the above application produces an error, but runs successfully without mirrord

with mirrord:
```
$ rm -fr hello.db && ./target/debug/mirrord exec ./bolt
2023/12/06 08:30:59 invalid argument
```

w/o mirrord:
```
$ rm -fr hello.db && ./bolt
```
My understanding is the discrepancy originates in the `syscall6` interception in golang code.
Do you know what could cause this? Let me know if any other info is needed to reproduce this. Happy to help debug this, if needed.

### Steps to Reproduce

see above

### Your operating system and version

$ lsb_release -a No LSB modules are available. Distributor ID: Ubuntu Description:    Ubuntu 23.04 Release:        23.04 Codename:       lunar

### Local process

BoltDB

**Comment by aviramha** [comment] 2023-12-06 09:36
Hey @Ngalstyan4 -  I suspect it wouldn't work because of relative path - mirrord always bypasses relative paths. Could you try this with a full path instead?

**Comment by aviramha** [comment] 2023-12-07 06:56
Got it! It is most likely we don't handle errors well (i.e given invalid argument instead of other error) - can you run the same with env `RUST_LOG=mirrord=trace` and provide it redacted?

**Comment by Ngalstyan4** [comment] 2023-12-07 07:05
Here:

[mirrord.txt](https://github.com/metalbear-co/mirrord/files/13596650/mirrord.txt)

Sorry, I tried disabling colors via `TERM=dumb RUST_LOG_STYLE=never RUST_LOG=mirrord=trace`, but it seems that did not succeed so the file has some non-ascii characters

**Comment by Ngalstyan4** [comment] 2023-12-08 01:17
Could you also log syscall results? I do not think they are in the logs above.
Could it be that `c_abi_syscall6_handler` does something strange with the result of some syscalls?

**Comment by meowjesty** [comment] 2023-12-11 17:58
Sorry for the late reply!

Kinda disregard my sample, it was produced amidst a ton of sneezing :sneezing_face:

Looks like the issue might be a missing hook, as boltdb calls this:

```go
func Fdatasync(fd int) (err error) {
	_, _, e1 := Syscall(SYS_FDATASYNC, uintptr(fd), 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
```

when initializing the database from a file, which results in a `bolt.Open: write /app/mirrord.db: bad file descriptor`.

**Comment by meowjesty** [comment] 2023-12-11 19:37
After hooking `fdatasync` and `pwrite64`, the error is now `file size too small` from here:

```go
func (db *DB) mmap(minsz int) (err error) {
	db.mmaplock.Lock()
	defer db.mmaplock.Unlock()

	info, err := db.file.Stat()
	if err != nil {
		return fmt.Errorf("mmap stat error: %s", err)
	} else if int(info.Size()) < db.pageSize*2 {
		return fmt.Errorf("file size too small")        <------
	}
    ...
}
```

Which is weird, because we successfully wrote a file that should be big, from the logs:

```sh
return=Ok(Ok(WriteFileResponse { written_amount: 16384 })) request=WriteLimitedFileRequest { remote_fd: 0, start_from: 0, write_bytes: 16384 }
```

**Comment by aviramha** [comment] 2023-12-11 19:50
Maybe we don't handle `stat` @meowjesty ?

**Comment by meowjesty** [comment] 2023-12-11 19:54
```sh
c_abi_syscall6_handler: syscall=75 param1=5 param2=0 param3=0 param4=0 param5=0 param6=0 <-- fdatasync
c_abi_syscall6_handler: syscall=281 param1=6 param2=140736140088552 param3=128 param4=0 param5=0 param6=0 <-- epoll_pwait
c_abi_syscall6_handler: syscall=281 param1=6 param2=140736140088552 param3=128 param4=0 param5=0 param6=0
c_abi_syscall6_handler: syscall=281 param1=6 param2=140736140088552 param3=128 param4=0 param5=0 param6=0
c_abi_syscall6_handler: syscall=5 param1=5 param2=824635466408 param3=0 param4=0 param5=0 param6=0 <-- fstat
c_abi_syscall6_handler: syscall=281 param1=6 param2=140736140088552 param3=128 param4=0 param5=0 param6=0
c_abi_syscall6_handler: syscall=281 param1=6 param2=140736140088552 param3=128 param4=0 param5=0 param6=0
c_abi_syscall6_handler: syscall=281 param1=6 param2=140736140088552 param3=128 param4=0 param5=0 param6=0
c_abi_syscall6_handler: syscall=281 param1=6 param2=140736140088552 param3=128 param4=0 param5=0 param6=0
c_abi_syscall6_handler: syscall=281 param1=6 param2=140736140088552 param3=128 param4=0 param5=0 param6=0
c_abi_syscall6_handler: syscall=281 param1=6 param2=140736140088552 param3=128 param4=0 param5=0 param6=0
c_abi_syscall6_handler: syscall=73 param1=5 param2=8 param3=0 param4=0 param5=0 param6=0 <-- flock
c_abi_syscall6_handler: syscall=3 param1=5 param2=0 param3=0 param4=0 param5=0 param6=0 <-- close
c_abi_syscall6_handler: syscall=281 param1=6 param2=140736140088552 param3=128 param4=0 param5=0 param6=0
```

Yeah, looks like `fstat` is not used in go?

**Comment by meowjesty** [comment] 2023-12-11 20:02
Now I think it's `pread64` failing:

```sh
c_abi_syscall6_handler: syscall=17 param1=5 param2=824634994152 param3=4096 param4=1024 param5=0 param6=0  <-- pread64
c_abi_syscall6_handler: syscall=17 param1=5 param2=824634994152 param3=4096 param4=2048 param5=0 param6=0
c_abi_syscall6_handler: syscall=17 param1=5 param2=824634994152 param3=4096 param4=4096 param5=0 param6=0
c_abi_syscall6_handler: syscall=17 param1=5 param2=824634994152 param3=4096 param4=8192 param5=0 param6=0
```

**Comment by meowjesty** [comment] 2023-12-11 20:12
And after hooking `pread64`, now it wants `mmap`:

```sh
c_abi_syscall6_handler: syscall=9 param1=0 param2=32768 param3=1 param4=1 param5=5 param6=0
```

**Comment by meowjesty** [comment] 2023-12-11 21:53
Alright, I'm reproducing this even when I bypass the file ops for the `.db` file that boltdb creates/manages.

It fails on `mmap`, even though the `fd` is not being handled by us, looks like our syscall handler for go might not be 100% working.

Just to clarify, you want to access this db file from your remote pod, or is it a local db file?

**Comment by Ngalstyan4** [comment] 2023-12-15 09:17
Remote - so no need for interception. 
I think the fix should work for me. Will try out tomorrow. Thanks for looking into this and promptly fixing it!!

**Comment by eyalb181** [comment] 2023-12-25 12:19
Closing this for now - @Ngalstyan4 let us know if the fix didn't work and we'll reopen.

**Closed by eyalb181** 2023-12-25 12:19 UTC
Labels: bug
