### ISSUE TITLE
failed to debug in macOS sonoma version 14.3

### ISSUE THREAD

**Issue by stonezdj** [metalbear-co/mirrord#2216] opened 2024-02-02 14:22 UTC
### Bug Description

Install VSCode plugin and enable mirrord.
-->Start Debugging
-->Select Target pod to mirror
Local process is launched and start to running.
But after send a request to the remote app, the local application should stopped at the break point, but it failed with this message.

```
....
2024-02-02T14:09:28.768543Z ERROR ThreadId(01) mirrord_layer::error: Error occured in Layer >> ProxyError(ConnectionClosed)
....
Detaching
```

The cluster is kind cluster

### Steps to Reproduce

1. Install VSCode plugin and enable mirrord.
2. Start Debugging
3. Select Target pod to mirror
4. Local process is launched and start to running.
5. Send a request to the remote app, the local application should stopped at the expected break point, but it failed with this message.
```
....
2024-02-02T14:09:28.768543Z ERROR ThreadId(01) mirrord_layer::error: Error occured in Layer >> ProxyError(ConnectionClosed)
....
Detaching
```

### Your operating system and version

macOS 14.3

### Local process

/Users/daojunz/homebrew/bin/mirrord of version 3.86.0

### Local process version

3.86.0

**Comment by t4lz** [comment] 2024-02-02 14:43
Duplicate of #2215

**Closed by t4lz** 2024-02-02 14:43 UTC
Labels: bug
