### ISSUE TITLE
npm module not found when running turbo app

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#2500] opened 2024-06-06 18:45 UTC
### Bug Description

Getting module not found when running some npm applications.

Seems like it could be related to #1956 and #1957, as we're getting the same error.

What is happening is that node is looking for module in a location that is relative to a path in our temp dir, but we want it to look for modules relative to the original path.
Not sure why our protections for that (hooking `_NSGetExecutablePath`, passing non-patched paths in exec args) did not prevent this. Maybe now the exec path is retrieved in a different way.

Volta-installed node is SIP-protected, unlike most node installations we've seen so far. I think this might be related to this issue.

### Steps to Reproduce

```
git clone git@github.com:t4lz/mirrord-sip-npm-issue.git
```
```
cd mirrord-sip-npm-issue
```
you might have to install vollta and then install npm and npx via vollta at this point.
```
npm run repro
```

### Backtrace

```shell
│ node:internal/modules/cjs/loader:1148
│   throw err;
│   ^
│ 
│ Error: Cannot find module '../lib/cli.js'
│ Require stack:
│ - /private/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
│     at Module._load (node:internal/modules/cjs/loader:986:27)
│     at Module.require (node:internal/modules/cjs/loader:1233:19)
│     at require (node:internal/modules/helpers:179:18)
│     at Object.<anonymous> (/private/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm:2:1)
│     at Module._compile (node:internal/modules/cjs/loader:1358:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
│     at Module.load (node:internal/modules/cjs/loader:1208:32)
│     at Module._load (node:internal/modules/cjs/loader:1024:12)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     '/private/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm'
│   ]
│ }
│ 
│ Node.js v20.14.0
└────>
┌ web#dev > cache bypass, force executing acec579587217658 
│ 2024-06-06T17:55:53.106830Z TRACE ThreadId(16) mirrord_layer::file::hooks: path Success(
│     "/dev/fd",
│ ) | open_options OpenOptionsInternal {
│     read: true,
│     write: false,
│     append: false,
│     truncate: false,
│     create: false,
│     create_new: false,
│ }
│ 2024-06-06T17:55:53.106950Z TRACE ThreadId(16) mirrord_layer::exec_utils: Executable /Users/tal/Documents/projects/test_projects/volta_test/my-turborepo/node_modules/turbo-darwin-arm64/bin/turbo called execve/posix_spawn
│ 2024-06-06T17:55:53.107190Z TRACE ThreadId(16) mirrord_sip::main: Using existing SIP-patched version of "/usr/bin/env": "/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/usr/bin/env"
│ 2024-06-06T17:55:53.107199Z TRACE ThreadId(16) mirrord_sip::main: Shebang points to: "/usr/bin/env". Patching the interpreter and making a version of "/Users/tal/.volta/tools/image/node/20.14.0/bin/npm" with an altered shebang 
│ at: "/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm"
│ 2024-06-06T17:55:53.107328Z TRACE ThreadId(16) mirrord_layer::exec_utils: exec arg: /Users/tal/.volta/tools/image/node/20.14.0/bin/npm
│ 2024-06-06T17:55:53.107331Z TRACE ThreadId(16) mirrord_layer::exec_utils: exec arg: run
│ 2024-06-06T17:55:53.107333Z TRACE ThreadId(16) mirrord_layer::exec_utils: exec arg: dev
│ node:internal/modules/cjs/loader:1148
│   throw err;
│   ^
│ 
│ Error: Cannot find module '../lib/cli.js'
│ Require stack:
│ - /private/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
│     at Module._load (node:internal/modules/cjs/loader:986:27)
│     at Module.require (node:internal/modules/cjs/loader:1233:19)
│     at require (node:internal/modules/helpers:179:18)
│     at Object.<anonymous> (/private/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm:2:1)
│     at Module._compile (node:internal/modules/cjs/loader:1358:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
│     at Module.load (node:internal/modules/cjs/loader:1208:32)
│     at Module._load (node:internal/modules/cjs/loader:1024:12)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     '/private/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm'
│   ]
│ }
│ 
│ Node.js v20.14.0
│ command finished with error: command (/Users/tal/Documents/projects/test_projects/volta_test/my-turborepo/apps/web) /Users/tal/.volta/tools/image/node/20.14.0/bin/npm run dev exited (1)
└────>
 ERROR  run failed: command  exited (1)
```

### Relevant Logs

```shell
│ 2024-06-06T17:55:53.105024Z TRACE ThreadId(15) mirrord_layer::exec_utils: Executable /Users/tal/Documents/projects/test_projects/volta_test/my-turborepo/node_modules/turbo-darwin-arm64/bin/turbo called execve/posix_spawn
│ 2024-06-06T17:55:53.105276Z TRACE ThreadId(15) mirrord_sip::main: Using existing SIP-patched version of "/usr/bin/env": "/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/usr/bin/env"
│ 2024-06-06T17:55:53.105289Z TRACE ThreadId(15) mirrord_sip::main: Shebang points to: "/usr/bin/env". Patching the interpreter and making a version of "/Users/tal/.volta/tools/image/node/20.14.0/bin/npm" with an altered shebang 
│ at: "/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm"
│ 2024-06-06T17:55:53.105867Z TRACE ThreadId(15) mirrord_layer::exec_utils: exec arg: /Users/tal/.volta/tools/image/node/20.14.0/bin/npm
│ 2024-06-06T17:55:53.105872Z TRACE ThreadId(15) mirrord_layer::exec_utils: exec arg: run
│ 2024-06-06T17:55:53.105874Z TRACE ThreadId(15) mirrord_layer::exec_utils: exec arg: dev
```

### Your operating system and version

MacOS 14.5

### Local process

npm, node, turbo

**Comment by aviramha** [comment] 2024-06-06 20:08
@t4lz suggested it might be because node is signed, but node is same node users had before the upgrade, so it's irrelevant.
In order to test it, I stripped the signature from turbo's Node and this still occurs.
I found that this command also reproduces it (needs to have "tampered binaries" for it to occur, atleast one run as @t4lz described)
`mirrord exec /var/folders/2h/fn_s1t8n0cqfc9x71yq845m40000gn/T/mirrord-bin/usr/bin/env node /var/folders/2h/fn_s1t8n0cqfc9x71yq845m40000gn/T/mirrord-bin/Users/aviramhassan/Code/mirrord-sip-npm-issue/node_modules/.bin/turbo run dev`

**Comment by aviramha** [comment] 2024-06-06 20:10
Also this
`mirrord exec env node /Users/aviramhassan/Code/mirrord-sip-npm-issue/node_modules/.bin/turbo run dev`

**Comment by aviramha** [comment] 2024-06-07 08:38
I found out that if you add `--no-daemon` to the command it works - I saw it connects to a socket and my theory now is that the script sends to the daemon it's path to load stuff for it, and we don't cover that flow.

**Comment by aviramha** [comment] 2024-06-07 14:33
ok, @t4lz might be right it being related to node being signed, since all the tester issues was actually when I tried to codesign to see if that fixes it, but each time I tried a different node binary (nvm vs volta) and when I patched both it always worked.

**Comment by aviramha** [comment] 2024-06-10 17:31
I thought it might be `getcwd` but nope :(

**Comment by t4lz** [comment] 2024-06-10 17:58
> I thought it might be `getcwd` but nope :(

I think we should be looking at ways an application can get the current executable's path, not the CWD's path.

**Comment by t4lz** [comment] 2024-06-10 18:13
This is where node threw an error for the user that faced this issue: https://github.com/nodejs/node/blob/v18.17.0/lib/internal/modules/cjs/loader.js#L1080

**Comment by aviramha** [comment] 2024-06-10 18:22
I know - I checked all symbols that are related to file access - Node needs to read the file and I can't see any access to it via any APIs.
Given it only happens with Turbo, I assume it might be Turbo doing something funky?
https://github.com/vercel/turbo/blob/main/crates/turbopack-cli/src/dev/mod.rs#L68

**Comment by t4lz** [comment] 2024-06-10 18:45
Here is the node error the user got, the one I got and posted in the issue's text is unfortunately a bit different:
```
│ node:internal/modules/cjs/loader:1080
│   throw err;
│   ^
│
│ Error: Cannot find module '/var/folders/j7/sjfkn72n6w17zd4z7b4b17d80000gq/T/mirrord
│ -bin/Users/some-user-name/.volta/tools/image/npm/9.6.4/bin/npm-cli.js'
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
│     at Module._load (node:internal/modules/cjs/loader:922:27)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:
│ 81:12)
│     at node:internal/main/run_main_module:23:47 {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: []
│ }
│
│ Node.js v18.17.0
│ command finished with error: command (/Users/some-user-name/some-app
│ ) /Users/some-user-name/.volta/tools/image/npm/9.6.4/bin/npm run dev exited (1)
└────>
┌ web-launcher#dev > cache bypass, force executing **redacted**
│ node:internal/modules/cjs/loader:1080
│   throw err;
│   ^
│
│ Error: Cannot find module '/var/folders/j7/sjfkn72n6w17zd4z7b4b17d80000gq/T/mirrord
│ -bin/Users/some-user-name/.volta/tools/image/npm/9.6.4/bin/npm-cli.js'
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
│     at Module._load (node:internal/modules/cjs/loader:922:27)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:
│ 81:12)
│     at node:internal/main/run_main_module:23:47 {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: []
│ }
│
│ Node.js v18.17.0
```

**Comment by aviramha** [comment] 2024-06-10 19:32
I think I found the problem:
argv:
```
["/Users/aviramhassan/.volta/tools/image/node/18.17.0/bin/node","/var/folders/2h/fn_s1t8n0cqfc9x71yq845m40000gn/T/mirrord-bin/Users/aviramhassan/.volta/tools/image/node/18.17.0/bin/npm","run","dev"]
```
which means node loads the npm script from the tmpbin then tries to find stuff in relation to it

**Comment by aviramha** [comment] 2024-06-10 19:53
ok. I found the issue. We don't get loaded - how I found out - I edited the sip patch `npm` file it's erroring about to print `proces.env` and saw that it's quite empty - turbo launches a new node, not inheriting any of the env to it, including DYLD!!!
AHHHHHhh

**Comment by t4lz** [comment] 2024-06-10 20:24
Nice. We could try changing the execve hook to add DYLD_INSERT_LIBRARIES to the env if not there, right?

**Comment by aviramha** [comment] 2024-06-10 20:33
Yup, on it.

**Comment by aviramha** [comment] 2024-06-11 07:46
We really don't like the env stripping - the argv stripping doesn't work - because `$TMPDIR` isn't set, then it tries to strip another path.
I'm changing the logic of SIP to just identify `mirrord-bin-RANDOM` - adding a random prefix (that is hardcoded) so we'll just identify based on `mirrord-bin-RANDOM`.
geeeeee

**Comment by aviramha** [comment] 2024-08-24 07:59
Probably related https://discord.com/channels/933706914808889356/950020257156833340/1276641706078372021

**Comment by aviramha** [comment] 2024-08-25 07:43
Reproduced with this example

**Comment by Razz4780** [comment] 2024-08-26 12:04
I've wasted a lot of time so much time, should've done it as the first step:
```
razz4780@razz4780-machine:~/MetalBear/mirrord-sip-npm-issue$ file /home/razz4780/MetalBear/mirrord-sip-npm-issue/node_modules/turbo-linux-64/bin/turbo
/home/razz4780/MetalBear/mirrord-sip-npm-issue/node_modules/turbo-linux-64/bin/turbo: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=53079539de775c245d18ee32c9754ccb04c8b1f8, stripped
```

;___;

**Comment by aviramha** [comment] 2024-08-26 12:09
oh no :O

**Comment by Razz4780** [comment] 2024-08-26 14:23
Ok, I managed to make it work. This has to merged into `turbo.json`:
```json
{
    "globalPassThroughEnv": ["MIRRORD_*", "LD_PRELOAD"]
}
```

**Comment by aviramha** [comment] 2024-08-26 15:03
perhaps add `DYLD_INSERT_LIBRARIES` as well? and add to mirrord.dev?

**Comment by Razz4780** [comment] 2024-08-26 15:45
> perhaps add `DYLD_INSERT_LIBRARIES` as well? and add to mirrord.dev?

https://github.com/metalbear-co/mirrord.dev/pull/335

**Closed** 2024-08-26 17:12 UTC
Labels: bug
